### ISSUE TITLE
i made the libx11 for macos 

### ISSUE THREAD

**Issue by JonnycatMeow** [Joalor64GH/BandLab-Radio-Player#1]
do you want it?

**Comment by Joalor64** [comment]
what does it do??

**Comment by JonnycatMeow** [comment]
i mean you added it for your linux

**Comment by JonnycatMeow** [comment]
the libx11

**Comment by JonnycatMeow** [comment]
![Screen Shot 2023-05-29 at 10 22 19 AM](https://github.com/Joalor64GH/BandLab-Radio-Player/assets/107599365/add2525b-ef7a-4711-9a19-d9c1f1e67278)

**Comment by Joalor64** [comment]
ohh okay
well then sure 👍

**Comment by JonnycatMeow** [comment]
where should i put it?

**Comment by Joalor64** [comment]
idk maybe under linux stuff
